# Generated by Django 3.2.7 on 2021-09-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='update_time'),
        ),
    ]
