# Generated by Django 3.2.7 on 2021-09-08 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_alter_profile_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='update_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 8, 7, 12, 16, 513915), null=True, verbose_name='update_time'),
        ),
    ]
