# Generated by Django 3.2.7 on 2021-09-08 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0005_repository'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'ordering': ['stars']},
        ),
    ]
