# Generated by Django 3.2.7 on 2021-09-09 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0006_alter_repository_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'ordering': ['-stars']},
        ),
    ]
