# Generated by Django 3.2.7 on 2021-09-11 15:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0007_alter_repository_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 11, 15, 52, 21, 938899, tzinfo=utc), verbose_name='update_time'),
        ),
    ]
